theme: hugo-theme-codex
title: codex
languageCode: en-us
baseURL: https://johnbedwards.io/
copyright: © 2021
canonifyURLs: true
disqusShortname: disqus_lXJY8DBG4I
ignoreErrors:
  - error-remote-getjson
params:
  dateFormat: Jan 2 2006
  github: https://github.com/john-b-edwards
  iconOrder:
    - Twitter
    - GitHub
  showPageTitleInTOC: no
  twitter: https://twitter.com/John_B_Edwards
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
menu:
  main:
    - identifier: home
      name: home
      title: Home
      url: /
      weight: 10
    - identifier: blog
      name: blog
      title: Blog
      url: /blog
      weight: 20
    - identifier: about
      name: about
      title: About
      url: /about
      weight: 30
    - identifier: resume
      name: resume
      title: Resume
      url: /resume
      weight: 40
      
